# Generated by Django 3.2 on 2023-08-13 08:12

import app.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', app.manager.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.PositiveIntegerField(max_length=12, unique=True),
        ),
    ]
