# Generated by Django 3.2 on 2023-08-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_customuser_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='angel_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='wallet',
            field=models.FloatField(default=0.0),
        ),
    ]
