# Generated by Django 3.2 on 2023-08-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_watchlist_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='margin',
            field=models.IntegerField(default=1),
        ),
    ]
