# Generated by Django 3.2 on 2023-08-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_customuser_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='margin',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
