# Generated by Django 3.2 on 2023-08-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_customuser_margin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='angel_user',
            new_name='api_order',
        ),
        migrations.AddField(
            model_name='customuser',
            name='access_token',
            field=models.CharField(blank=True, default='', max_length=420, null=True),
        ),
    ]
