# Generated by Django 3.2 on 2023-09-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='intraday',
        ),
        migrations.AddField(
            model_name='order',
            name='product_type',
            field=models.CharField(choices=[('Intraday', 'Intraday'), ('Long Term', 'Long Term')], default='Intraday', max_length=9),
        ),
    ]
