# Generated by Django 3.2 on 2023-09-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20230901_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_type',
            new_name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('Market', 'Market'), ('Limit', 'Limit')], default='Market', max_length=7),
        ),
    ]
