# Generated by Django 3.2 on 2023-09-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20230901_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(choices=[('Intraday', 'Intraday'), ('Margin', 'Margin')], default='Intraday', max_length=9),
        ),
    ]
