# Generated by Django 3.2 on 2023-09-01 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20230902_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='api_order',
            new_name='api_orders',
        ),
    ]
