# Generated by Django 3.2 on 2023-09-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_rename_api_order_customuser_api_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='wallet',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
