# Generated by Django 3.2 on 2023-09-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20230902_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='wallet',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='position',
            name='buy_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='position',
            name='pnl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='position',
            name='sell_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='position',
            name='total_buy_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='position',
            name='total_sell_price',
            field=models.FloatField(default=0.0),
        ),
    ]
