# Generated by Django 3.2 on 2023-09-16 12:08

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_position_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=app.models.generate_unique_id, editable=False, max_length=10, unique=True),
        ),
    ]
