# Generated by Django 3.2 on 2023-09-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.CharField(default='01eb0c350e6140ae9455d419bdc569e2', max_length=366, unique=True),
        ),
    ]
