# Generated by Django 3.2 on 2023-09-16 12:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.CharField(default='e302b6ea0ccd4776ad812281ce8d8eab', max_length=366, unique=True),
        ),
    ]
