# Generated by Django 3.2 on 2023-09-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20230916_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='73bddcb82da045ada24d3fd3697fea0c', editable=False, unique=True),
        ),
    ]
