# Generated by Django 3.2 on 2023-09-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_customuser_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='access_token',
        ),
    ]
