# Generated by Django 3.2 on 2023-09-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_remove_customuser_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='308eb1952ab3442680576db6ab62fe8b', editable=False, unique=True),
        ),
    ]
