# Generated by Django 3.2 on 2023-09-16 13:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_remove_customuser_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default=uuid.UUID('f8681c73-dfe6-4c44-8d46-1794ac15c677'), editable=False, unique=True),
        ),
    ]
