# Generated by Django 3.2 on 2023-09-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='d072dcc83a8043b68964261d1bf0f7ba', editable=False, unique=True),
        ),
    ]
