# Generated by Django 3.2 on 2023-09-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='status',
            field=models.CharField(choices=[('Favourites', 'Favourites'), ('My list', 'My list'), ('Must Watch', 'Must Watch'), ('Random', 'Random'), ('Passive', 'Passive'), ('Priority', 'Priority'), ('Active', 'Active')], default='Favourites', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='ad328215ac6041c4ad0bf6bb017a79b2', editable=False, unique=True),
        ),
    ]
