# Generated by Django 3.2 on 2023-09-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20230918_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='3548837c7e334d99877e58bfc6958632', unique=True),
        ),
    ]
