# Generated by Django 3.2 on 2023-09-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='segment',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='position',
            name='segment',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='segment',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='478bdd06395e483baf82f9ec5744420e', unique=True),
        ),
    ]
