# Generated by Django 3.2 on 2023-09-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_alter_customuser_access_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='status',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='3990d859673d4c6a87e06ad5f9250ca8', unique=True),
        ),
    ]
