# Generated by Django 3.2 on 2023-09-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20230921_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='token',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='843fb597eea243ff9f5ae9e9f79d4f52', unique=True),
        ),
    ]
