# Generated by Django 3.2 on 2023-09-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20230922_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='token',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='1ed820c027494aa58382f3ca3ee1ee51', unique=True),
        ),
    ]
