# Generated by Django 3.2 on 2023-09-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20230924_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='5021a3dae8304ce6a0a7555ed573f8a3', unique=True),
        ),
    ]
