# Generated by Django 4.2.5 on 2023-10-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='is_holding',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='98057927c98447c48f33f3b47212ba90', unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(choices=[('INTRADAY', 'INTRADAY'), ('CARRYFORWARD', 'CARRYFORWARD')], default='INTRADAY', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('MARKET', 'MARKET'), ('LIMIT', 'LIMIT')], default='MARKET', max_length=7),
        ),
        migrations.AlterField(
            model_name='position',
            name='product',
            field=models.CharField(choices=[('INTRADAY', 'INTRADAY'), ('CARRYFORWARD', 'CARRYFORWARD')], default='INTRADAY', max_length=15),
        ),
    ]
