# Generated by Django 4.2.5 on 2023-10-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_position_is_holding_alter_customuser_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='token',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='d3f8592ff6914f30ba463cbcf9bdc685', unique=True),
        ),
    ]
