# Generated by Django 4.2.5 on 2023-10-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_remove_position_token_alter_customuser_access_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='pnl',
            new_name='relised_pnl',
        ),
        migrations.AddField(
            model_name='position',
            name='unrelised_pnl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='76af40378d1e4daea403f7f952ba4bf3', unique=True),
        ),
    ]
