# Generated by Django 4.2.5 on 2023-10-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_rename_pnl_position_relised_pnl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='total_buy_price',
        ),
        migrations.RemoveField(
            model_name='position',
            name='total_sell_price',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='58af1518951e4759b97384c68d4bf7bc', unique=True),
        ),
    ]
