# Generated by Django 4.2.5 on 2023-10-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_remove_position_total_buy_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='832b05b47650431886dabeb62f8a67c5', unique=True),
        ),
    ]
