# Generated by Django 4.2.5 on 2023-10-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_alter_customuser_access_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='relised_pnl',
            new_name='realised_pnl',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='unrelised_pnl',
            new_name='unrealised_pnl',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='9506cb46d4794a32bbc6a344bebe51a2', unique=True),
        ),
    ]
