# Generated by Django 4.2.5 on 2023-10-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_rename_relised_pnl_position_realised_pnl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='4e82775a23f343a9b719695d935fd946', unique=True),
        ),
    ]
