# Generated by Django 4.2.5 on 2023-10-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='631a6f74772241b390e9a07ac9a9653b', unique=True),
        ),
    ]
