# Generated by Django 4.2.5 on 2023-10-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='c8872ce6ba5a4cefa5971b7986b6f416', unique=True),
        ),
    ]
