# Generated by Django 4.2.5 on 2023-10-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='charges',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='position',
            name='security_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='b5a8bd3d69ec403f92d25999d107d8b1', unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('initiated', 'initiated'), ('pending', 'pending'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('failed', 'failed')], default='pending', max_length=10),
        ),
    ]
