# Generated by Django 4.2.5 on 2023-10-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_order_charges_position_security_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='token',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='7317acc1a75946f9a81567cb6f185d92', unique=True),
        ),
    ]
