# Generated by Django 4.2.5 on 2023-10-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_position_token_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='d5cb5cb50eab4ee6a1035697a347b43a', unique=True),
        ),
    ]
