# Generated by Django 4.2.5 on 2023-10-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='last_traded_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='060adf1bc4ce4e6c8845d9d10f396ffb', unique=True),
        ),
    ]
