# Generated by Django 4.2.5 on 2023-10-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_position_last_traded_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ifsc_code',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='customuser',
            name='upi_id',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='08a7b3aadca2423faaef50331b669ed3', unique=True),
        ),
    ]
