# Generated by Django 4.2.5 on 2023-10-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_customuser_ifsc_code_customuser_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='1aae403223f646988fa8c18c2709f2bb', unique=True),
        ),
    ]
