# Generated by Django 4.2.5 on 2023-10-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_remove_customuser_name_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='b42d43dbe8d143a6b131e828e8cdc33e', unique=True),
        ),
    ]
