# Generated by Django 4.2.5 on 2023-10-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='4f02cb93e21047868f15b9a6f60db609', unique=True),
        ),
    ]
