# Generated by Django 4.2.5 on 2023-10-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='8d72f18f21574d2eb50288da7235adfe', unique=True),
        ),
    ]
