# Generated by Django 4.2.5 on 2023-10-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='cb992bbe430043f299a45e58d6be182f', unique=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='tag',
            field=models.CharField(default='Favourites', max_length=20),
        ),
    ]
