# Generated by Django 4.2.5 on 2023-10-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_position_is_closed_alter_customuser_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bank_account_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_account_number',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='68260f6f7c1b495985db9cbcc9893c2c', unique=True),
        ),
    ]
