# Generated by Django 4.2.5 on 2023-10-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_customuser_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='9a150507172246b88b30f2e63a3c1666', unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='margin',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
