# Generated by Django 4.2.5 on 2023-10-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_alter_customuser_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='margin_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='d44beeb072464126bbdf70d723592607', unique=True),
        ),
    ]
