# Generated by Django 4.2.5 on 2023-10-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_customuser_margin_used_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='110f39cebe794ba99ae294e9aee9124f', unique=True),
        ),
    ]
