# Generated by Django 4.2.5 on 2023-10-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='7a5f7d514e8e456786617d46690e53d3', unique=True),
        ),
    ]
