# Generated by Django 4.2.5 on 2023-10-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_alter_customuser_access_token_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='3af78b9790c84668a8140e892c9fb186', unique=True),
        ),
    ]
