# Generated by Django 4.2.5 on 2023-10-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_alter_customuser_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='default_watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(default='', max_length=150)),
                ('stock', models.CharField(default='', max_length=150)),
            ],
            options={
                'verbose_name': 'Default Watchlist',
                'verbose_name_plural': 'Default Watchlist',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='9e557987616045e39446da9767a0cedf', unique=True),
        ),
    ]
