# Generated by Django 4.2.5 on 2023-11-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_remarks_alter_customuser_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='384ab0fe4fa64b6c927aa8d34ea4eab3', unique=True),
        ),
    ]
