# Generated by Django 4.2.5 on 2023-11-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_position_last_traded_alter_customuser_access_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='last_traded',
            new_name='last_traded_datetime',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='f028da4c1b84477d9ed057b0416567ab', unique=True),
        ),
    ]
