# Generated by Django 4.2.5 on 2023-11-04 18:56

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_rename_last_traded_position_last_traded_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='position_id',
            field=models.CharField(default=app.models.generate_unique_id, editable=False, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='position',
            name='stoploss',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='position',
            name='target',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='b51ff1c0251a4bc0b8bd4e78bb4d4a03', unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='last_traded_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
