# Generated by Django 4.2.5 on 2023-11-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_position_position_id_position_stoploss_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='default_watchlist',
            old_name='stock',
            new_name='symbol',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='67cb8a7d8e7c48148c60c5fabd05aed5', unique=True),
        ),
    ]
