# Generated by Django 4.2.5 on 2023-11-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_rename_stock_default_watchlist_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='412d91dbdf024d308510b439161c92dc', unique=True),
        ),
    ]
