# Generated by Django 4.2.5 on 2023-11-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0088_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='ad98d911ec3946e987884dbb61f05e46', unique=True),
        ),
    ]
