# Generated by Django 4.2.5 on 2023-11-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0090_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='2faa06d00aff4bd880393524273bc260', unique=True),
        ),
    ]
