# Generated by Django 4.2.5 on 2023-11-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='92c5f47336b5478b94e1d6cffeadf7aa', unique=True),
        ),
    ]
