# Generated by Django 4.2.5 on 2023-12-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='b22772278097455d9fe53296f8893032', unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='margin_used',
            field=models.FloatField(default=0.0),
        ),
    ]
