# Generated by Django 4.2.5 on 2023-12-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0093_alter_customuser_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='a768d67f3c6d41f69efbc946c63e4f59', unique=True),
        ),
    ]
