# Generated by Django 4.2.5 on 2023-12-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='aeca97d4efc843e59b519404355b3280', unique=True),
        ),
    ]
