# Generated by Django 4.2.5 on 2023-12-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0097_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stoploss',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='target',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='7a92ec6a41954374ab457be70ff39e79', unique=True),
        ),
    ]
