# Generated by Django 4.2.5 on 2023-12-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0098_order_stoploss_order_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='cdc7a61449d244ff93e999248e800bb5', unique=True),
        ),
    ]
