# Generated by Django 4.2.5 on 2023-12-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0099_alter_customuser_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='stoploss',
        ),
        migrations.RemoveField(
            model_name='position',
            name='target',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='04a339f858b04ab5912bff1c2926e9f3', unique=True),
        ),
    ]
