# Generated by Django 4.2.5 on 2023-12-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0100_remove_position_stoploss_remove_position_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED')], default='REQUESTED', max_length=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('WITHDRAW', 'WITHDRAW'), ('DEPOSIT', 'DEPOSIT')], default='WITHDRAW', max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='2db2a093723045f3bf33c41015d6ba44', unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(default=0.0),
        ),
        migrations.DeleteModel(
            name='Withdrawn_Request',
        ),
    ]
