# Generated by Django 4.2.5 on 2023-12-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0101_transaction_status_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='38cba4becd4749edb5b15fba25068d79', unique=True),
        ),
    ]
