# Generated by Django 4.2.5 on 2023-12-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0102_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='eb264e810fd540ea923af95944e176f1', unique=True),
        ),
    ]
