# Generated by Django 4.2.5 on 2023-12-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0103_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='958bda0dc9294ea0ab5149e1ed122c73', unique=True),
        ),
    ]
