# Generated by Django 4.2.5 on 2023-12-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0104_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='7f3e075c3841472faa447f320fb50245', unique=True),
        ),
    ]
