# Generated by Django 4.2.5 on 2023-12-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0105_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='stoploss',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='position',
            name='target',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='aceb91be91c043619cb0befe3402bc64', unique=True),
        ),
    ]
