# Generated by Django 4.2.5 on 2023-12-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0106_position_stoploss_position_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='f168c207e2c94d7981f05aa6eead5280', unique=True),
        ),
    ]
