# Generated by Django 4.2.5 on 2023-12-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0107_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='b2a89a8469ba425fb77bf44b197fa994', unique=True),
        ),
    ]
