# Generated by Django 4.2.5 on 2023-12-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0108_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='8618b5462b8746f2acbc1781354ee39e', unique=True),
        ),
    ]
