# Generated by Django 4.2.5 on 2023-12-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0110_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='c2ac67e831994b7ca9771894d575df38', unique=True),
        ),
    ]
