# Generated by Django 4.2.5 on 2023-12-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0111_watchlist_price_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='close',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='high',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='low',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='open',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='004dcb3bfd3c41c4b6c6208b61050474', unique=True),
        ),
    ]
