# Generated by Django 4.2.5 on 2023-12-31 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0112_watchlist_close_watchlist_high_watchlist_low_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.position'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='e3721df4143e4116870f76c289863dd4', unique=True),
        ),
    ]
