# Generated by Django 4.2.5 on 2023-12-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0113_order_position_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='cb4f3f69203c4f099cbc1e6241e694dd', unique=True),
        ),
    ]
