# Generated by Django 4.2.5 on 2024-01-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0114_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='instrument_key',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='916461dac0314dabbf9ab35012d6a025', unique=True),
        ),
    ]
