# Generated by Django 4.2.5 on 2024-01-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0115_order_instrument_key_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='ecea04b1c07a47a7807382f424c62eea', unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='instrument_key',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
