# Generated by Django 4.2.5 on 2024-01-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0116_alter_customuser_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='close',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='high',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='low',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='open',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='price',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='instrument_key',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='37ad3bd02c724890acb2e1c50c2d06bd', unique=True),
        ),
    ]
