# Generated by Django 4.2.5 on 2024-01-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0117_remove_watchlist_close_remove_watchlist_high_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='stock',
            new_name='symbol',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='adcfdf4553d3451b89389896415a198e', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'symbol')},
        ),
    ]
