# Generated by Django 4.2.5 on 2024-01-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0118_rename_stock_watchlist_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='instrument_key',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='02f7a70731c34f85b9e67fda46b70a9e', unique=True),
        ),
    ]
