# Generated by Django 4.2.5 on 2024-01-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0119_position_instrument_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='63ba0508c74e4e6983dcd7d8e302bb50', unique=True),
        ),
    ]
