# Generated by Django 4.2.5 on 2024-01-30 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0120_alter_customuser_access_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='default_watchlist',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='92a4fd4af1914fdfb7de3e7814d7a8bd', unique=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='tag',
            field=models.CharField(default='#@default', max_length=20),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
