# Generated by Django 4.2.5 on 2024-03-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0121_delete_default_watchlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='instrument_key',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='close',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='high',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='low',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='ltp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='open',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='3fa02938dfa647928b927d974d37a4fd', unique=True),
        ),
    ]
