# Generated by Django 4.2.5 on 2024-06-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0122_remove_watchlist_instrument_key_watchlist_close_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='50d96e83dbf34bc38ad3dae525a01aaf', unique=True),
        ),
        migrations.CreateModel(
            name='symbols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='', max_length=150)),
                ('segment', models.CharField(default='', max_length=150)),
                ('instrument_key', models.CharField(default='', max_length=150)),
                ('ltp', models.FloatField(default=0)),
                ('open', models.FloatField(default=0)),
                ('close', models.FloatField(default=0)),
                ('high', models.FloatField(default=0)),
                ('low', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'unique_together': {('symbol', 'segment')},
            },
        ),
    ]
