# Generated by Django 4.2.5 on 2024-06-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0123_alter_customuser_access_token_symbols'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='b885ffa98a3046fbbf2eaf918a0b7ba1', unique=True),
        ),
    ]
