# Generated by Django 4.2.5 on 2024-06-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0124_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='ed8f6093ff00461fa74412c5947a264b', unique=True),
        ),
    ]
