# Generated by Django 4.2.5 on 2024-06-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0125_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='3707fb9f1540436bb0001ef169ae4e0a', unique=True),
        ),
    ]
