# Generated by Django 4.2.7 on 2024-06-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0126_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='677405657bcf416c8b6356107e3217a7', unique=True),
        ),
    ]
