# Generated by Django 4.2.5 on 2024-06-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0127_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='51656714731f4c5eba26b2433a11cede', unique=True),
        ),
    ]
