# Generated by Django 4.2.5 on 2024-06-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0128_alter_customuser_access_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='token',
            new_name='instrument_key',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='7ed676787c3a439787d3d46226126c96', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'symbol', 'segment')},
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='close',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='high',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='low',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='ltp',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='open',
        ),
    ]
