# Generated by Django 4.2.5 on 2024-06-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0130_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='a695c7f88fad4f939b1919bdc84168d1', unique=True),
        ),
    ]
