# Generated by Django 4.2.5 on 2024-06-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0131_alter_customuser_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_key', models.CharField(max_length=100)),
                ('exchange_token', models.CharField(blank=True, max_length=20, null=True)),
                ('tradingsymbol', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('last_price', models.FloatField()),
                ('expiry', models.CharField(blank=True, max_length=20, null=True)),
                ('strike', models.FloatField(blank=True, null=True)),
                ('tick_size', models.FloatField(blank=True, null=True)),
                ('lot_size', models.IntegerField(blank=True, null=True)),
                ('instrument_type', models.CharField(max_length=20)),
                ('option_type', models.CharField(blank=True, max_length=20, null=True)),
                ('exchange', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='0f4a93ae473743c08c027d23528db1c5', unique=True),
        ),
    ]
