# Generated by Django 4.2.5 on 2024-06-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0132_instrument_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='f229cbf5fca84ad194f757498e4f006a', unique=True),
        ),
    ]
