# Generated by Django 4.2.5 on 2024-06-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0133_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='7e80b3ccd0b843c485c3eba98d505a8c', unique=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='last_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
