# Generated by Django 4.2.7 on 2024-06-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0134_alter_customuser_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='d4b5be3ef56c43cabff12c23a8c0a70b', unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(choices=[('Intraday', 'Intraday'), ('Carryforward', 'Carryforward')], default='Intraday', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('Market', 'Market'), ('Limit', 'Limit')], default='Market', max_length=7),
        ),
        migrations.AlterField(
            model_name='position',
            name='product',
            field=models.CharField(choices=[('Intraday', 'Intraday'), ('Carryforward', 'Carryforward')], default='Intraday', max_length=15),
        ),
    ]
