# Generated by Django 4.2.7 on 2024-06-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0135_alter_customuser_access_token_alter_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='9ea143814eda468a95aae981a697da8d', unique=True),
        ),
    ]
