# Generated by Django 4.2.7 on 2024-06-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0137_alter_customuser_access_token_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='128e3b46342d4ff08c7177eb55925bae', unique=True),
        ),
    ]
