# Generated by Django 4.2.5 on 2024-06-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0138_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='eb11e7e549ff45108d806034e1a20672', unique=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='tag',
            field=models.CharField(default='Favourites', max_length=20),
        ),
    ]
