# Generated by Django 4.2.5 on 2024-07-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0140_position_lot_size_watchlist_lot_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='7c36a691ebd2478497f2f8a6e4464bec', unique=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='lot_size',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
