# Generated by Django 4.2.7 on 2024-07-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0141_alter_customuser_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='8b450e4d7e0c4aba9fbf15b6ed1c5d69', unique=True),
        ),
    ]
