# Generated by Django 4.2.5 on 2024-07-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0142_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact Us Request', 'verbose_name_plural': 'Contact Requests'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='38fd025bbb184316bda5cf63bbaca43c', unique=True),
        ),
    ]
