# Generated by Django 4.2.5 on 2024-07-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0144_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='614d93c594f14efba684e91fa663f6eb', unique=True),
        ),
    ]
