# Generated by Django 4.2.7 on 2024-07-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0145_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='b0b704f62f644fa89fbddcd19417a45a', unique=True),
        ),
    ]
