# Generated by Django 4.2.5 on 2024-07-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0146_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='8e63011e23fa48d083e39e4050316d32', unique=True),
        ),
    ]
