# Generated by Django 5.0.3 on 2024-07-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0148_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='shoonya_symbol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='1e884ebc4dcf4a7ab5880b954b19e7f5', unique=True),
        ),
    ]
