# Generated by Django 5.0.3 on 2024-07-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0149_instrument_shoonya_symbol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoonya_Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=10)),
                ('token', models.CharField(max_length=20, unique=True)),
                ('lot_size', models.IntegerField()),
                ('symbol', models.CharField(max_length=20)),
                ('trading_symbol', models.CharField(max_length=20)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('instrument', models.CharField(max_length=20)),
                ('option_type', models.CharField(blank=True, max_length=5, null=True)),
                ('strike_price', models.FloatField(blank=True, null=True)),
                ('tick_size', models.FloatField()),
                ('precision', models.IntegerField(blank=True, null=True)),
                ('multiplier', models.FloatField(blank=True, null=True)),
                ('gngd', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='shoonya_symbol',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='bb1f1e1d68a3446b88a495c3320a985c', unique=True),
        ),
    ]
