# Generated by Django 5.0.3 on 2024-07-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0150_shoonya_instrument_remove_instrument_shoonya_symbol_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoonya_instrument',
            old_name='gngd',
            new_name='exchange_token',
        ),
        migrations.RenameField(
            model_name='shoonya_instrument',
            old_name='token',
            new_name='tradingsymbol',
        ),
        migrations.RemoveField(
            model_name='shoonya_instrument',
            name='expiry',
        ),
        migrations.RemoveField(
            model_name='shoonya_instrument',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='shoonya_instrument',
            name='lot_size',
        ),
        migrations.RemoveField(
            model_name='shoonya_instrument',
            name='multiplier',
        ),
        migrations.RemoveField(
            model_name='shoonya_instrument',
            name='option_type',
        ),
        migrations.RemoveField(
            model_name='shoonya_instrument',
            name='precision',
        ),
        migrations.RemoveField(
            model_name='shoonya_instrument',
            name='strike_price',
        ),
        migrations.RemoveField(
            model_name='shoonya_instrument',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='shoonya_instrument',
            name='tick_size',
        ),
        migrations.RemoveField(
            model_name='shoonya_instrument',
            name='trading_symbol',
        ),
        migrations.AddField(
            model_name='shoonya_instrument',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='3bb5b0a5b3004cf4a6fe9489f6c68a6b', unique=True),
        ),
        migrations.AlterField(
            model_name='shoonya_instrument',
            name='exchange',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
