# Generated by Django 5.0.3 on 2024-07-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0151_rename_gngd_shoonya_instrument_exchange_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='766c98c528bb4399b62bf48ba17fc0dd', unique=True),
        ),
        migrations.AlterField(
            model_name='shoonya_instrument',
            name='tradingsymbol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
