# Generated by Django 5.0.3 on 2024-07-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0152_alter_customuser_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoonya_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('response', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='bbbd50fb02434eb696ca11bcbb71381d', unique=True),
        ),
    ]
