# Generated by Django 5.0.3 on 2024-07-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0153_shoonya_orders_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoonya_instrument',
            options={'verbose_name': 'Shoonya Instrument', 'verbose_name_plural': 'Shoonya Instruments'},
        ),
        migrations.AlterModelOptions(
            name='shoonya_orders',
            options={'verbose_name': 'Shoonya Order', 'verbose_name_plural': 'Shoonya Orders'},
        ),
        migrations.AddField(
            model_name='symbols',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='d1a0b96d67904b7b800706cbec7a7648', unique=True),
        ),
    ]
