# Generated by Django 4.2.7 on 2024-07-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0153_shoonya_orders_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='7bd15cd725a44c5fbc982d2fd6fbca69', unique=True),
        ),
    ]
