# Generated by Django 4.2.7 on 2024-07-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0154_alter_customuser_access_token'),
        ('app', '0154_alter_shoonya_instrument_options_and_more'),
    ]

    operations = [
    ]
