# Generated by Django 5.0.3 on 2024-07-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0155_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pan_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='ea62f5855aec435b900c6a2e29b55049', unique=True),
        ),
    ]
