# Generated by Django 5.0.3 on 2024-07-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0156_customuser_pan_number_alter_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.UUIDField(default='1bfac7c6435542d18e4c3e967b065a4d', unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pan_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
