# Generated by Django 4.2.7 on 2024-07-24 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0155_merge_20240724_1901'),
        ('app', '0157_alter_customuser_access_token_and_more'),
    ]

    operations = [
    ]
