# Generated by Django 4.2.7 on 2024-07-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0158_merge_20240724_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='access_token',
        ),
    ]
