# Generated by Django 4.2.7 on 2024-07-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0159_remove_customuser_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbols',
            name='last_day_close',
            field=models.FloatField(default=0),
        ),
    ]
