# Generated by Django 5.0.3 on 2024-08-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0160_symbols_last_day_close'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnstockBalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('balance', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Onstock Balance',
                'verbose_name_plural': 'Onstock Balance History',
            },
        ),
    ]
