# Generated by Django 5.0.3 on 2024-08-04 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0161_onstockbalancehistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='onstockbalancehistory',
            unique_together={('datetime',)},
        ),
    ]
