# Generated by Django 5.0.3 on 2024-08-04 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0162_alter_onstockbalancehistory_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnstockBalanceHistory',
        ),
    ]
