# Generated by Django 5.0.3 on 2024-08-04 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0164_onstockbalancehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onstockbalancehistory',
            old_name='date',
            new_name='datefield',
        ),
        migrations.AlterUniqueTogether(
            name='onstockbalancehistory',
            unique_together={('datefield',)},
        ),
    ]
