# Generated by Django 4.2.7 on 2024-08-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0165_rename_date_onstockbalancehistory_datefield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onstockbalancehistory',
            name='brokerage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='onstockbalancehistory',
            name='pnl',
            field=models.FloatField(default=0.0),
        ),
    ]
