# Generated by Django 5.0.3 on 2024-08-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0167_alter_contact_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onstockbalancehistory',
            name='deposit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='onstockbalancehistory',
            name='withdrawn',
            field=models.FloatField(default=0.0),
        ),
    ]
