# Generated by Django 5.0.3 on 2024-09-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0168_onstockbalancehistory_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='automatic_close',
            field=models.BooleanField(default=False),
        ),
    ]
