# Generated by Django 5.0.3 on 2024-09-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0169_order_automatic_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.FloatField(default=0.0),
        ),
    ]
