# Generated by Django 5.0.3 on 2024-09-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0170_transaction_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='checksum',
            field=models.CharField(default='', editable=False, max_length=550),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('REQUESTED', 'REQUESTED'), ('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED')], default='REQUESTED', max_length=15),
        ),
    ]
