# Generated by Django 5.0.3 on 2024-09-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0171_transaction_checksum_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='checksum',
            field=models.CharField(blank=True, default='', editable=False, max_length=550, null=True),
        ),
    ]
