# Generated by Django 5.0.3 on 2024-09-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0173_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='on_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='on_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('REQUESTED', 'REQUESTED'), ('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='REQUESTED', max_length=15),
        ),
    ]
