# Generated by Django 4.2.7 on 2024-10-08 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0176_customuser_carryforward_buy_charge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnstockUserBalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datefield', models.DateField(default=django.utils.timezone.now)),
                ('balance', models.FloatField(default=0.0)),
                ('pnl', models.FloatField(default=0.0)),
                ('brokerage', models.FloatField(default=0.0)),
                ('withdrawn', models.FloatField(default=0.0)),
                ('deposit', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onstock Users Balance',
                'verbose_name_plural': 'User Balance History',
                'unique_together': {('datefield', 'user')},
            },
        ),
    ]
