# Generated by Django 3.2 on 2023-08-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.FloatField(default=0.5)),
                ('buy_charge', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
