# Generated by Django 3.2 on 2023-08-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basic',
            options={'verbose_name': 'Basic Settings', 'verbose_name_plural': 'Basics'},
        ),
        migrations.AddField(
            model_name='basic',
            name='sell_charge',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
