# Generated by Django 3.2 on 2023-08-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_basic_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basic',
            options={'verbose_name': 'Basic Settings', 'verbose_name_plural': 'Basic Settings'},
        ),
    ]
