# Generated by Django 3.2 on 2023-09-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_basic_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=120)),
                ('api_key', models.CharField(default='', max_length=555)),
            ],
            options={
                'verbose_name': 'Api Settings',
                'verbose_name_plural': 'Api Settings',
            },
        ),
    ]
