# Generated by Django 3.2 on 2023-09-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('market_dates', models.ManyToManyField(blank=True, to='settings.dates')),
            ],
            options={
                'verbose_name': 'Market',
                'verbose_name_plural': 'Market Settings',
            },
        ),
    ]
