# Generated by Django 4.2.5 on 2023-10-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_dates_market'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Market',
            new_name='mcx_market_time',
        ),
        migrations.AlterModelOptions(
            name='mcx_market_time',
            options={'verbose_name': 'MCX Market Setting', 'verbose_name_plural': 'MCX Market Settings'},
        ),
        migrations.CreateModel(
            name='nse_market_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('market_dates', models.ManyToManyField(blank=True, to='settings.dates')),
            ],
            options={
                'verbose_name': 'NSE Market Setting',
                'verbose_name_plural': 'NSE Market Settings',
            },
        ),
    ]
