# Generated by Django 4.2.5 on 2023-10-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_rename_market_mcx_market_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.FloatField(default=0.5)),
                ('intraday_buy_charge', models.PositiveIntegerField(default=0)),
                ('intraday_sell_charge', models.PositiveIntegerField(default=0)),
                ('carryforward_buy_charge', models.PositiveIntegerField(default=0)),
                ('carryforward_sell_charge', models.PositiveIntegerField(default=0)),
                ('order_closing', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Basic Settings',
                'verbose_name_plural': 'Basic Settings',
            },
        ),
        migrations.DeleteModel(
            name='basic',
        ),
    ]
