# Generated by Django 4.2.5 on 2023-10-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_charges_delete_basic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charges',
            options={'verbose_name': 'Charges', 'verbose_name_plural': 'Charges'},
        ),
        migrations.RenameField(
            model_name='charges',
            old_name='order_closing',
            new_name='order_closing_charge',
        ),
    ]
