# Generated by Django 4.2.5 on 2023-11-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_alter_charges_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AngelApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Angel One API',
                'verbose_name_plural': 'Market API',
            },
        ),
    ]
