# Generated by Django 4.2.5 on 2023-12-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_angelapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoonyaApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=200)),
                ('vendor_code', models.CharField(max_length=100)),
                ('apikey', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Shoonya API',
                'verbose_name_plural': 'Shoonya API',
            },
        ),
    ]
