# Generated by Django 4.2.5 on 2023-12-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_shoonyaapi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoonyaapi',
            old_name='apikey',
            new_name='api_key',
        ),
    ]
