# Generated by Django 4.2.5 on 2023-12-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_rename_apikey_shoonyaapi_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option_Lot_Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('segment', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Options Lot Size',
                'verbose_name_plural': 'Options Lot sizes',
            },
        ),
    ]
