# Generated by Django 4.2.5 on 2023-12-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_option_lot_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angelapi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
