# Generated by Django 4.2.5 on 2023-12-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_alter_angelapi_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upstox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(default='', max_length=100)),
                ('redirect_uri', models.CharField(default='https://onstock.in/upstox_cred', max_length=120)),
                ('token', models.CharField(max_length=200)),
                ('api_key', models.CharField(max_length=1000)),
                ('secret_key', models.CharField(max_length=300)),
                ('code', models.CharField(default='Leave it blank', max_length=100)),
                ('access_code', models.CharField(default='Leave it blank', max_length=1000)),
            ],
            options={
                'verbose_name': 'Upstox',
                'verbose_name_plural': 'Upstox API',
            },
        ),
    ]
