# Generated by Django 4.2.5 on 2023-12-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_upstox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upstox',
            old_name='access_code',
            new_name='access_token',
        ),
    ]
