# Generated by Django 4.2.5 on 2023-12-22 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_rename_access_code_upstox_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upstox',
            name='token',
        ),
    ]
