# Generated by Django 4.2.5 on 2023-12-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_remove_upstox_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='upstox',
            name='symbol_csv_file',
            field=models.FileField(blank=True, null=True, upload_to='csv_files/'),
        ),
    ]
