# Generated by Django 4.2.5 on 2024-01-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0018_upstox_symbol_csv_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpstoxAccessTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(default='access token', max_length=1000)),
            ],
            options={
                'verbose_name': 'Upstox Access Token',
                'verbose_name_plural': 'Upstox Access Tokens',
            },
        ),
    ]
