# Generated by Django 4.2.5 on 2024-06-10 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0019_upstoxaccesstokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upstox',
            name='symbol_csv_file',
        ),
    ]
