# Generated by Django 4.2.5 on 2024-06-10 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0020_remove_upstox_symbol_csv_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upstox',
            old_name='redirect_uri',
            new_name='redirect_url',
        ),
    ]
