# Generated by Django 4.2.5 on 2024-06-10 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0021_rename_redirect_uri_upstox_redirect_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upstox',
            old_name='redirect_url',
            new_name='redirect_uri',
        ),
    ]
