# Generated by Django 4.2.5 on 2024-07-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0022_rename_redirect_url_upstox_redirect_uri'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AngelApi',
        ),
        migrations.DeleteModel(
            name='Option_Lot_Size',
        ),
    ]
