# Generated by Django 4.2.5 on 2024-07-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0023_delete_angelapi_delete_option_lot_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpstoxAccessTokens',
        ),
    ]
