# Generated by Django 4.2.5 on 2024-07-07 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0024_delete_upstoxaccesstokens'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Api',
        ),
    ]
