# Generated by Django 5.0.3 on 2024-09-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0025_delete_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='charges',
            name='manipulate_100_to_200',
            field=models.FloatField(default=1.25),
        ),
        migrations.AddField(
            model_name='charges',
            name='manipulate_200_to_400',
            field=models.FloatField(default=1.45),
        ),
        migrations.AddField(
            model_name='charges',
            name='manipulate_25_to_50',
            field=models.FloatField(default=0.45),
        ),
        migrations.AddField(
            model_name='charges',
            name='manipulate_400_or_above',
            field=models.FloatField(default=2.25),
        ),
        migrations.AddField(
            model_name='charges',
            name='manipulate_50_to_100',
            field=models.FloatField(default=0.65),
        ),
        migrations.AddField(
            model_name='charges',
            name='manipulate_5_to_25',
            field=models.FloatField(default=0.25),
        ),
    ]
