# Generated by Django 5.0.3 on 2024-09-05 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0026_charges_manipulate_100_to_200_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcx_market_time',
            name='position_close_time',
            field=models.TimeField(default=datetime.time(23, 20)),
        ),
        migrations.AddField(
            model_name='nse_market_time',
            name='position_close_time',
            field=models.TimeField(default=datetime.time(15, 20)),
        ),
    ]
