# Generated by Django 5.0.3 on 2024-09-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0027_mcx_market_time_position_close_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(default='', max_length=500)),
                ('upi_token', models.CharField(default='', max_length=500)),
                ('key', models.CharField(default='', max_length=500)),
                ('payu_marchent_key', models.CharField(default='', max_length=500)),
                ('payu_marchent_salt', models.CharField(default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Payment Gateway Setting',
                'verbose_name_plural': 'Payment Gateway',
            },
        ),
    ]
