# Generated by Django 4.2.7 on 2024-10-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0028_paymentgateway'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charges',
            name='carryforward_buy_charge',
        ),
        migrations.RemoveField(
            model_name='charges',
            name='carryforward_sell_charge',
        ),
        migrations.RemoveField(
            model_name='charges',
            name='intraday_buy_charge',
        ),
        migrations.RemoveField(
            model_name='charges',
            name='intraday_sell_charge',
        ),
    ]
