# Generated by Django 4.2.5 on 2023-11-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ca',
            name='link',
            field=models.CharField(default='#', max_length=250),
        ),
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.CharField(default='#', max_length=250),
        ),
    ]
